// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/optum/runiac/pkg/config (interfaces: Stepper)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	config "github.com/optum/runiac/pkg/config"
	reflect "reflect"
)

// MockStepper is a mock of Stepper interface
type MockStepper struct {
	ctrl     *gomock.Controller
	recorder *MockStepperMockRecorder
}

// MockStepperMockRecorder is the mock recorder for MockStepper
type MockStepperMockRecorder struct {
	mock *MockStepper
}

// NewMockStepper creates a new mock instance
func NewMockStepper(ctrl *gomock.Controller) *MockStepper {
	mock := &MockStepper{ctrl: ctrl}
	mock.recorder = &MockStepperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStepper) EXPECT() *MockStepperMockRecorder {
	return m.recorder
}

// ExecuteStep mocks base method
func (m *MockStepper) ExecuteStep(arg0 config.StepExecution) config.StepOutput {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteStep", arg0)
	ret0, _ := ret[0].(config.StepOutput)
	return ret0
}

// ExecuteStep indicates an expected call of ExecuteStep
func (mr *MockStepperMockRecorder) ExecuteStep(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteStep", reflect.TypeOf((*MockStepper)(nil).ExecuteStep), arg0)
}

// ExecuteStepDestroy mocks base method
func (m *MockStepper) ExecuteStepDestroy(arg0 config.StepExecution) config.StepOutput {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteStepDestroy", arg0)
	ret0, _ := ret[0].(config.StepOutput)
	return ret0
}

// ExecuteStepDestroy indicates an expected call of ExecuteStepDestroy
func (mr *MockStepperMockRecorder) ExecuteStepDestroy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteStepDestroy", reflect.TypeOf((*MockStepper)(nil).ExecuteStepDestroy), arg0)
}

// ExecuteStepTests mocks base method
func (m *MockStepper) ExecuteStepTests(arg0 config.StepExecution) config.StepTestOutput {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteStepTests", arg0)
	ret0, _ := ret[0].(config.StepTestOutput)
	return ret0
}

// ExecuteStepTests indicates an expected call of ExecuteStepTests
func (mr *MockStepperMockRecorder) ExecuteStepTests(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteStepTests", reflect.TypeOf((*MockStepper)(nil).ExecuteStepTests), arg0)
}

// PreExecute mocks base method
func (m *MockStepper) PreExecute(arg0 config.StepExecution) (config.StepExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreExecute", arg0)
	ret0, _ := ret[0].(config.StepExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreExecute indicates an expected call of PreExecute
func (mr *MockStepperMockRecorder) PreExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreExecute", reflect.TypeOf((*MockStepper)(nil).PreExecute), arg0)
}
