name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.4"
      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v0.1.0
        with:
          gotestsum_version: 1.6.4
      - name: "go test"
        run: |
          rm -rf ./reports && mkdir ./reports;
          gotestsum --format standard-verbose --junitfile ./reports/junit.xml --raw-command -- go test -parallel 5 --json ./...;
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: reports/*.xml
