name: Unit Test Results

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  unit-test-results:
    name: Unit Test Results
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion != 'skipped'

    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
         name: Unit Test Results
         path: ./artifacts
         
      - name: Extract Artifacts
        run: |
          for file in artifacts/*.zip
          do
            if [ -f "$file" ]
            then
              dir="${file/%.zip/}"
              mkdir -p "$dir"
              unzip -d "$dir" "$file"
            fi
          done

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.15.1
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          files: "artifacts/*/**/*.xml"
